plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

version = mod_version
group = 'plus.dragons'
archivesBaseName = 'forge-create-dragons-plus'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                create_dragons_plus {
                    source sourceSets.main
                }
            }
        }
        client {}
        server { args '--nogui' }
        gameTestServer {
            workingDirectory project.file('run/gametest')
            property 'forge.enabledGameTestNamespaces', 'create_dragons_plus'
            args '--nogui'
        }
    }
}

repositories {
    // 只在最前面加这两行镜像，确保你的网络能下到东西
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://bmclapi2.bangbang93.com/maven' }

    maven {
        name = 'Create'
        url = 'https://maven.createmod.net'
    }
    maven {
        name = 'Registrate'
        url = 'https://maven.ithundxr.dev/mirror'
    }
    maven {
        name = 'Jared'
        url = 'https://maven.blamejared.com/'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
    maven {
        name = 'FallenBreath'
        url = 'https://maven.fallenbreath.me/releases'
    }
    mavenCentral()
    //flatDir { dir "${rootProject.projectDir}/../forge-create-enchantment-industry/build/libs" }
    //flatDir { dir "${rootProject.projectDir}/../forge-create-integrated-farming/build/libs" }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation(fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}:slim")) { transitive = false }
    implementation fg.deobf("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    compileOnly fg.deobf("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly fg.deobf("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")

    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:15.2.0.27")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:15.2.0.27")

    compileOnly fg.deobf("maven.modrinth:create-dreams-and-desires:1.20.1-0.2c.PREBETA")
    compileOnly fg.deobf("maven.modrinth:create-garnished:2.1.7.b+1.20.1-forge")

    jarJar(group: 'me.fallenbreath', name: 'conditional-mixin-forge', version: '[0.6.0,1.0.0)') {
        jarJar.pin(it, '0.6.3')
    }
    implementation "me.fallenbreath:conditional-mixin-forge:0.6.3"

    implementation "io.github.llamalad7:mixinextras-common:0.4.1"
    implementation(fg.deobf("io.github.llamalad7:mixinextras-forge:0.4.1"))

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    //runtimeOnly fg.deobf("create_enchantment_industry:create_enchantment_industry:1.3.6-for-create-6.0.8")
    //runtimeOnly fg.deobf("forge-create-integrated-farming:forge-create-integrated-farming:1.0.1-mc1.20.1:all")
}

mixin {
    add sourceSets.main, "create_dragons_plus.refmap.json"
    config "create_dragons_plus.mixins.json"
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand project.properties
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "Forge-Create: Dragons Plus",
                "Specification-Vendor"    : "DragonsPlusMinecraft",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : mod_version,
                "Implementation-Vendor"   : "DragonsPlusMinecraft",
                "MixinConfigs"            : "create_dragons_plus.mixins.json"
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.named('jarJar') {
    finalizedBy 'reobfJarJar'
}

tasks.named('build') {
    dependsOn tasks.named('jarJar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}